### ISSUE TITLE
Project-3(Timmy, Jonathan, Jeff)

### ISSUE THREAD

**Issue by jtfragale** [ga-dc/project3-gallery#100]
Link to repo:

https://github.com/jtfragale/Project-3-front-end
https://github.com/jtfragale/Project-3-backend

Link to deployed app:

https://globalcup.surge.sh/

Things you'd like specific feedback on:

we know we need to refactor for an updated deployment later for Global Cup 2.0

**Comment by megmaciver13** [comment]
## Hard Requirements
☑️ The backend API for your application is deployed to Heroku and the frontend is deployed to Surge or GitHub Pages
☑️ The commit history of your repo(s) show a roughly equal number of commits from each group member.

## Evaluation Requirements

### Back End Technology
Score: Progressing

Overall, your back-end code looks great. Great job incorporating JWT authentication. The file structure is neat and organized, as is your code. I like the way you added comments describing all the CRUD methods in your `teams` controller to increase readability of your code. You could consider adding comments to the other files for comment consistency.

Technically, your back end appears to have just one non-User model, but I do see that you have [sub-documents](http://mongoosejs.com/docs/subdocs.html) in your Team model. In order to make each of these a model, you would run `mongoose.model(...)` for each schema and separate them out into their own files (per convention).

I added a few comments via issues about setting up your schemas and keeping your routes RESTful.

### Front End Technology
Score: Performing

Overall, this is well done! You have a sufficiently complex tree of components in your front end, and your components are well organized.

In the future, consider creating an images directory in `public` to store all images, instead of storing them in a component directory. For the most part, you did a great job naming your components in a descriptive, yet concise manner. `Container`, for instance, could be a bit more descriptive.

In striving for DRY code, I would challenge you to use reusable components each time you have to present or store data for all ten players. I have included some suggestions/comments on that in specific issues in your front-end repo, as well as some additional ideas for cleaning up the code a bit.

### Code Quality
Score: Performing

Overall, both your front end and back end have high quality code. Your back-end is particularly neatly done. As indicated in the issues in your front-end repo, there are a few players where you could clean up your code a bit and make it more DRY. On the back end, be sure to keep your routes RESTful and delineate what your models are.

In the front end, your `App.js` is rather long, so including inline comments for each class method could help enhance clarity and readability.

### Deployment and Functionality
Score: Performing

Both your front end and back end are deployed and looking good!

### Planning/Process/Submission
Score: Performing

Your planning materials in the front-end repo show that you came together as a team to plan a shared vision for your app. User stories can always further enhance the clarity of this vision.

I would highly suggest giving both your front-end and back-end repos a readme to describe all the things you implemented in each (express, jwt auth, React, etc) and then also link to the other repo for more context on the full-stack app. When potential employers visit your GitHub repos, it's helpful to have a readme supplement to explain what each repo contains!

__

Overall, I commend you guys for working well as a team. You seemed to communicate clearly and have well-defined roles within your group. This experience will be invaluable to draw upon as you interview for positions that inevitably will have a team aspect to them. Your soccer app is executed!
