### ISSUE TITLE
Starving Artist - Brandon, Hannah, Mahwish

### ISSUE THREAD

**Issue by BrandonS8** [ga-dc/project3-gallery#101]
Link to repo:
Backend:
https://github.com/HannahAurand/Starving_Artist_MEN/
Frontend: 
https://github.com/HannahAurand/Starving_Artist_React

Link to deployed app:
http://starving-artist.surge.sh/

Things you'd like specific feedback on:
* how images are stored and deleted in the backend
* Using git revert to go back to previous code without breaking anything else?
* best practice for css in react/reusing css on multiple components
* Is this similar to working in a real work group? 
* Why you can't refresh or go back using back button on surge, [would this fix it](https://github.com/ReactTraining/react-router/blob/master/FAQ.md#why-doesnt-my-application-render-after-refreshing)?

**Comment by jabyess** [comment]
Comments! Feedback! Great work.


## Back End: Excelling
* I love that you got file upload working! That's great and definitely challenging.
* Brandon getting all fancy using promises to seed the data.
* Multiple models = :+1:
* Your backend routes are RESTful which is a huge bonus. Plus you moved the upload into a different route.
* Full crud functionality for both stores and products. Amazeballs

## Front End: Performing
* So much cool attention to detail, like:
  * When the store is empty, there's a sad face
  * Hover animations
  * randomized colors on page load
  * Button styling
* It's mostly responsive (with some stuff you could probably fix easily)
* In some cases you're using state where you don't need to: like in StoreCard.js to randomize the colors. You can just use a regular variable for that. Only use state if you need to update something without reloading the page.

## Code Quality: Performing
* You've got appropriate comments, but not too many.
* Some code included that is commented out, but not a lot

## Deployment and Functionality: Performing
* Everything works!
* You have some unnecessary console logs (either logging response data or undefined stuff), totally worth getting rid of those.

## Planning / Process / Submission: Progressing
* Not much planning for the front end. Would love to have seen some wireframes!
* Back end has more fleshed out things, I really like the MVP/Bronze/Gold priorities too.

## Comments
Images: The way you have it working now is pretty great. Maybe in a production application you'd upload to an external service (like amazon s3 or something). Ideally you'd store the file path or url in the model and delete the file when you delete the product.

Git revert: This is a tricky one, since you can't delete commits. It's more like: make a new commit with changes that are exactly the opposite of the last commit. Sometimes this does break stuff, but it's the best way to do things.

CSS: Make a single .css file for every component (like you have) but also have a file that's imported at a common parent (like App.js). This file should contain the shared css. Then just make sure your classes are named properly.

Working in a group: Generally, yes the process is roughly the same  but obviously it's gonna depend on the company and team process. Git branching should be similar, but in some places your code must be reviewed by someone else before you can merge to master.

Loading on refresh: yes. It's a consequence of how routers work on static hosts. The static host only serves a page at `/` (which serves index.html, which has your react script on it). The hash router thing seems like a good solution, and that link is a really good explanation.
