### ISSUE TITLE
Project 3 (Angela, Laura, Qya) 

### ISSUE THREAD

**Issue by angmalone** [ga-dc/project3-gallery#102]
front end: https://github.com/angmalone/project3-frontend
back end: https://github.com/angmalone/project3-backend

deployed app: tbd lol

**Comment by angmalone** [comment]
http://cheap-wash.surge.sh/

**Comment by 0xZakk** [comment]
# Project Evaluation

For details on how your project was evaluated, check out the [evaluation rubric](https://git.generalassemb.ly/ga-wdi-exercises/project3/blob/master/evaluation.md)

## Hard Requirements

- [X] The backend API for your application is deployed to Heroku and the frontend is deployed to Surge or GitHub Pages
- [X] The commit history of your repo(s) show a roughly equal number of commits from each group member.

## Evaluation Requirements

### Back-end Technology

**Score: Performing**

I love how clean and organized your back end is! This is really great! Your code is so clean and well written. I've left some tips and things to consider in issues on your back end repo, but most of the things are small tips you could do to make it better. Y'all did a really great job on implementing the back end!

### Front-end Technology

**Score: Performing**

Your front end is definitely complex enough. The biggest piece of feedback I have for you is to consider cleaning up the file structure. Specifically, try moving all your components into a `components/` directory and then maybe try give each component it's own directory. That will clean up your codebase a lot!

Another tip I have for y'all is one we discussed on Thursday of Project Week: consider moving all your state up to the `App` component and just managing it there. If you do that, then all of the rest of your components can be function components (which is another tip - consider migrating your class components that don't have any state to be functional components).

Finally, it looks like y'all have started abstracting your api calles to the `api/` directory - definitely finish doing that as it will help really clean up your codebase! Another option to consider after that is migrating your state to Redux. 

### Code Quality

**Score: Performing**

The code in your back end is really well organized and well formatted. As I said above, the only feedback I can offer is minor things. Your front end is also in a good spot. I think y'all would benefit from abstracting your markup in to more components. That's something a lot of people new to React have resistance too, but it makes your app so much cleaner! Build a ton of small components (atoms, from the Reusable Components lesson) and your markup will look a lot cleaner.

### Deployment & Functionality

**Score: Progressing**

There are a few errors and bugs still with the production app, but they appear to all be small and isolated to the front end. With a little bit of time and effort, y'all could bring this up to a Performing by finishing moving your API calls to the `apis/` directory and fixing some of the errors around querying your database.

### Planning / Process / Submission

**Score: Excelling**

Your branching strategy is great - really well done! Ya'll also have a great amount of planning in here. My only suggestion on your submission is to make it so to give the backend repository a readme and to make sure the readme for both your front end and back end is in Markdown (right now it looks like the front end readme is just plain text). 

---

Overall, y'alls project is really great! I hope you keep working on this because I think it's something that you and other students would really get value out from!
