### ISSUE TITLE
Nhi, Mei, Daniel

### ISSUE THREAD

**Issue by dbf8** [ga-dc/project3-gallery#103]
Link to repo: https://github.com/dbf8/Wobble_Front_End/
https://github.com/dbf8/Wobble_Back_End/
Link to deployed app: wobble.surge.sh
https://wobble-back-end.herokuapp.com/api/websites

**Comment by megmaciver13** [comment]
## Hard Requirements
☑️ The backend API for your application is deployed to Heroku and the frontend is deployed to Surge or GitHub Pages
☑️ The commit history of your repo(s) show a roughly equal number of commits from each group member.

## Evaluation Requirements

### Back End Technology
Score: Performing

Overall, your back-end code looks really great. It's well organized and easy to read!

Technically your back end has just one model with a comment subdocument. But I do see that you have a fully realized schema for comments. In order to make each of these a model, you would run `mongoose.model(...)` for each schema and separate them out into their own files (per convention). Outside the scope of a class project that requires two models, subdocuments can be the right approach!

To modularize your code a bit more and keep each file shorter, you could create a website controller to handle all requests that start with the path '/apis/websites/.' I have included a few more specific suggestions in issues in the repo.

### Front End Technology
Score: Excelling

Your front-end code is in good shape, and the way the page renders is fantastic. Very cool idea incorporating an iframe, which we didn't cover in class.

In the future, consider creating an images directory in public to store all images, instead of storing them in a component directory.

You did a great job naming the components in a concise, descriptive way. The `Button` component file looks to be mistakenly placed within the `Nav` components folder. For an even more advanced file tree, you could have a `components` folder in src, and put all the component folders in there. This would help visually break apart the long list of files/folders in src.

I have included specific suggestions on how you could refactor your code in issues in the front-end repo.

### Code Quality
Score: Performing

Overall, your code is well written and well organized. There are a few places that could benefit from a code review. For instance, it looks like `Review.js` is an empty component in your front end? If that was meant for something you didn't have time to develop, consider commiting it to a development branch, so that the version on your public Github is cleaned up! 

I like the inline comments that you included in the `index.js` file of your back end. In longer files like that, inline comments can really help with context and better readability.

One suggestion I have for you is to always challenge yourselves to think about how you can further abstract your code into smaller, more readable pieces. For instance, creating a controller in the back-end to handle requests starting with '/api/websites/'. On the front-end, that means thinking about where you can break down your code into even futher components.

### Deployment and Functionality
Score: Performing

Your front end and back end are deployed! Huzzah. 

It looks like the request to handle new comments (referenced in an axios request in the `CommentAdd` component) isn't yet set up. Once that is set up, you can get your functionality to add comments working!

### Planning/Process/Submission
Score: Performing

That's great to include wireframing in your front-end repo to show your intentionality with this project and the ability to carry through. 

In future group experiences, you should work on increased communication among team members to better balance out responsibilities - and in this case, could have had a more evenly distributed commit history. In web development (as in many fields!), working on a team is essential to creating the best product you can. You never know what soft skills and technical skills you could glean from open-minded collaboration with your colleagues.

I really like the outline of your readme in both repos, listing tools used, authors (with links!), how to get started. (Note: Your front repo does not utilize Express. It does, however, utilize 'axios' - which just happens to make calls to an Express server.) Talk about your workflow! You could add a section about anything you would refactor, as well as a section about what features you would build on next. This info can help to illustrate your understanding of these technologies and your ability to understand context in a project. A pro move would be to put the link to the deployed site at the top of the page where it currently says "No description, website, or topics provided." under the repo title. That way can immediately go see your deployed beauty!

__

Overall, your Wobble project looks really nice. There is room for a code review, and room for lessons to take away regarding teamwork and group communication. This project shows you have come a long way in the course, and I hope y'all continue on track!
