### ISSUE TITLE
Project 3 Kevin, Ai Yen, Hyojin

### ISSUE THREAD

**Issue by KBuck2018** [ga-dc/project3-gallery#104]
Link to repo: https://github.com/KBuck2018/coffeerunsthroughme-backend
https://github.com/hyojinsarchet/coffeerunsthroughme-frontend/tree/master
Link to deployed app:

http://woozy-answer.surge.sh/
https://coffeerunsthroughme.herokuapp.com/main

Things you'd like specific feedback on:

**Comment by jabyess** [comment]
Notes here!

## Back End: Progressing
* Back end code is well organized. I like that you have signup and login functionality.
  * I tried to sign up with a username that already existed and it didn't let me, but there was no error message or warning! It works though.
* Once signed in, it pulled default data from the database! Does that mean all users are editing the same set of data?
* Able to update values from the frontend, so that's cool. I couldn't get it to work using postman or curl. Values persist on reload.
* Can't create new rows?
* Two models: users and models.js (maybe call that caffeine instead!?)

## Front End: Performing
* All the components are broken out logically - thinking in react!
* When I click update, I have no idea whether it saved or not. Some visual confirmation would be nice.
* The animations on the fun facts page are neato.


## Code Quality: Progressing 
* Great use of the spread operator, especially with props and state.
* Some unnecessarily commented out code - not just code comments.
* Not many code comments describing what's going on
* Frontend code is overall really good.

## Deployment and Functionality: Performing
* Not sure what specific feedback I have. Everything works, you have a custom domain. Some errors in the browser console but those are easily fixed and don't seem to affect functionality?

## Planning / Process / Submission: Excelling
* Love all the planning docs, t e wireframes, user stories, all good stuff.
* You clearly used git branching, with everyone working on their own features (though I know you ran into some problems with the workflow).
* Good stuff overall. Only thing missing is explanations for why you chose to do certain things and not others.
