### ISSUE TITLE
group 1 matt, jacob, sanjay

### ISSUE THREAD

**Issue by jacobg1** [ga-dc/project3-gallery#80]
Meme generator: users can enter text and get a randomly generated pic

mvp: user enters text, pulls random pic for api, appends text to pic 
bronze: char count/limit, query pictures based on text
silver: random text, meme show page where user can get new pic or text
gold: toggle text on/off, users with show page, create image alphabet. true image context (link image to text). moving dead pixel for extra awesome user experience. also combine angular and rails app.

**Comment by jacobg1** [comment]
dankMemes: https://jacobg1.github.io/text_2_pix_client
dankMemes API: https://meme-gen-api.herokuapp.com/memes

REPOS:
Jacob-
client: https://github.com/jacobg1/text_2_pix_client
server: https://github.com/jacobg1/text_2_pix_server
Matt-
client: https://github.com/mattcfilbert/text_2_pix_client
server: https://github.com/mattcfilbert/text_2_pix_server
Sanjay-
client: https://github.com/sanjaywallah/text_2_pix_client 
server: https://github.com/sanjaywallah/text_2_pix_server

**Comment by jsm13** [comment]
# Feedback
## Back-end Technology 2
- No back-end present, or unable to persist data and return JSON
- Lacking more than one model
- **Includes 2 models**
- Includes many well-structured models, and advanced functionality such as authorization, 3rd-party API integration, or other technology not covered in class

Great job! The models make sense and describe your use case without anything extraneous. The models are well related and the controller actions all make sense. One thing to note is that controller actions should always have some response. Currently the `delete` actions just do their work on the database and don't provide a response -- you want them to send something simple like: `{message: 'Meme deleted'}`

## Front-end Technology 2
- No use of Angular code
- Basic front-end with at least 1 Angular controller
- **Front-end makes appropriate use of Angular controllers and states with ui-router.**
- In addition to appropriate Angular use, includes 1 Angular topic not covered in class. Makes use of multiple custom directives

Excellent use of a variety of APIs and a well organized app. You get a lot of functionality out of a couple of views. One organizational suggestion I would make is breaking the `meme.controller` file into two, one for show and one for index. One implementation change I would make (and we didn't cover in class) is that `$resource` is great for use with URLs we want to perform RESTful actions on (generally our own endpoints). If we are only ever making `get` requests as with the third-party APIs, the `$http` service (which works like `$.ajax`) is sufficient. You need to unpack the responses yourself but this is often more clear and explicit. Great job over all!

## Code Quality 2
- Minimal functional code is present
- Code lacks proper formatting, includes commented out, non-functional code, or otherwise contains major issues of quality (DRY, naming, etc)
- **Code is well-formatted, well-named, and contains few style / quality issues**
- No major code quality issues, Angular code follows John Pappa style guide, and follows techniques such as separation of concerns, abstraction, and encapsulation

### Did you...
- [x] Keep your code DRY
> Good job on this for the most part. One thing you could add to both of your controllers is an `init` function that takes care of all the work that needs to be done when that controller is instantiated. That way you will be able to just call `init()` instead of `$window.reload`
- [x] Maintain consistent code style? You're working in teams, but you're only making one app per team. Make sure it looks like a unified effort.
> Very well done here. This is more something to pay attention to in Angular as the conventions of Rails tend to lead to consistency anyway. You did a great job having `services` written and named consistently.
- [x] Commit early and often? Don't be afraid to break something because you can always go back in time to a previous version.
> Great job! Tons of commits and for the most part the messages are really good. Check out [this article](https://chris.beams.io/posts/git-commit/) for a deep dive into commit message best practices.
- [x] Deploy early and often? Deploy your work as early as possible, even if you don't really have anything completed. Heroku issues always pop up. Don't be caught short just before the submission deadline!
> Don't think you all deployed super early but I think early enough to sort out any problems. Good work!
- [x] Name things appropriately? Do your naming conventions make sense? Would another developer be able to look at your app and understand what everything is? (See "self-documenting").
> Variable and file naming conventions follow best practices and the code is clear to navigate. Nice!
- [x] Comment when necessary? Comments can help to explain the intent (i.e., the what and the why) of a piece of code. These allow the next developer to understand the purpose and decide what can be adjusted to achieve the same goal.
> Lots of comments offer lots of explination. Sometimes when a comment labels a set of lines, it's an indicator that they could be combined into a well named function. Specifically, I'm thinking about [this block](https://github.com/jacobg1/text_2_pix_client/blob/master/js/controller/meme.controller.js#L26-L30) in the controller which could be put in a `fetchData` method.
- [x] Ensure code is well-formatted? Are you indenting consistently? Can we find the start and end of every div, curly brace, etc? Organizing the hierarchy is key to understanding.
> Formatting is good overall. Some places are a little crowded. It is always good to leave a line of whitespace after a block of code like [the function definition here](https://github.com/jacobg1/text_2_pix_client/blob/master/js/controller/meme.controller.js#L73-L74). Even though the next line is a comment, having a blank line before that comment will make the code more legible.

## Deployment and Functionality 2
- Application is not deployed, and contains minimal functionality
- Application contains minimal functionality, but deployment is non-functional, or application contains major errors when used
- **Application contains no major errors, is deployed correctly, and contains a custom Heroku app name appropriate for the app.**
- App has advanced functionality that works with minimal errors, and may make use of advanced tools such as APIs, plugins, etc. App may be deployed to a service other than Heroku (e.g. Digital Ocean).

App is deployed and functional. Great job! Use of local storage is a really clever way to give users control of their experience without letting them add questionable content to your database.

## Planning / Process / Submission 1.5
- No submission received, or submission does not contain basic documentation of planning (ERD, wireframes, commit history, etc)
- **App is submitted, with basic evidence of planning. Documentation exists, but lacks common areas such as setup instructions, description of application functionality and link to deployed application**
- Submission contains **clear evidence of planning**, **adequate documentation**, include all from previous category, as well as additional information such as unsolved issues.
- Submission includes everything in previous category, as well as evidence of proper teamwork, such as feature branching, code review, github issue / user story tracking, and justification of technical decisions.

Good job! Consider a bit more of a write up on how the planning proccess went and have that narrative supported by pictues. Keep in mind the README likely will be looked at by some less technical people -- a story will help bring the planning material depth and context.

### Contribution Guidelines
- [x] Each member of your group must have an individual commit history to your project's repositories
> That's a lot of commits! Great job with a shared effort -- lots of commits from everyone!
- [ ] Each project should include a readme.md that provides information as to the roles of each member of the group. It should include the responsibilities of each member and their accomplishments.
> I'd include this in the expanded description of your planning described above.
- [x] Each member of your group is expected to present for an equal amount of time during project presentations
> Great presentation! Neat app and great engagement with the class.

It was really great working with you all. You pulled together a great project, worked well as a team, and from what I understand enjoyed the proccess. Great job! If you have any particular questions, I can clarify anything or I can help with anything, let me know!
