### ISSUE TITLE
esGApe - Grant Brown, Sam Gehret, Samuel Haile

### ISSUE THREAD

**Issue by grantnathanielbrown** [ga-dc/project3-gallery#99]
Link to repo:
FRONT END: https://github.com/samgehret/esGApe-front-end
BACK END: https://github.com/samgehret/esGApe-back-end

Link to deployed app:

http://disillusioned-pet.surge.sh/

Things you'd like specific feedback on:

**Comment by 0xZakk** [comment]
# Project Evaluation

For details on how your project was evaluated, check out the [evaluation rubric](https://git.generalassemb.ly/ga-wdi-exercises/project3/blob/master/evaluation.md)

## Hard Requirements

- [X] The backend API for your application is deployed to Heroku and the frontend is deployed to Surge or GitHub Pages
- [X] The commit history of your repo(s) show a roughly equal number of commits from each group member.

## Evaluation Requirements

### Back-end Technology

**Score: Excelling**

Y'all have a well built and feature-rich back-end API. I like the way you've organized your `app.js` file so it's mostly just configuration and all the logic is happining elsewhere, I think that's great. Additionally, the way you're organized everything (i.e. the filesystem) is really clear.

It looks like your HappyHour and LunchSpot models are almost identical. Given that's the case, I suggest making this work with 1 model (you effectively have one model twice rather than two models). `Restaurant` could be a better model to go with. You could then have two subdocument models for a `LunchDeal` and a `HappyHour` (perhaps a restaurant has both or different lunch deals or happy hours on different days of the week). Moving towards a model set like that would give y'all a lot more flexibility. 

I suggest also looking for a way to reuse the comment model you're defining in both `HappyHour.js` and `LunchSpot.js` - both of these models are identical so you should only define it once and reuse it (DRY!).

You're creating comments via a `put` request to `/happyhours/comments/:id` or `/lunchspots/comments/:id`. That breaks away from REST. You're creating instances of a resource here (a Comment), so you want to follow REST by having these routes and actions:

| Route | Action |
| --- | --- |
| GET `/happyhours/:id/comments` | Get all comments for a happy hour |
| GET `/happyhours/:id/comments/:id` | Get a comment for a happy hour |
| POST `/happyhours/:id/comments` | Create a new comment under a happy hour |
| PUT `/happyhours/:id/comments/:id` | Update a commend under a happy hour |
| DELETE `/happyhours/:id/comments/:id` | Delete a comment under a happy hour |

You may not need all of these (like getting a comment by Id), but it's important to follow REST as your application grows so resources and performing CRUD on resources is easy to manage!

### Front-end Technology

**Score: Performing**

Your front end is in a good place! You've got a couple of places where the code isn't DRY or coule be cleaned up a big, so see the issues for those. Additionally, I'd suggest breaking your app up into more components and thinking about Atomic Design (atoms, molecules, and organisms) when approaching your components. 

### Code Quality

**Score: Progressing**

Your back end is well written and well organized. Think through your naming as much as you can to make sure things are clear.

I would suggest refactoring your front end when you all have time, perhaps while reviewing the lesson on Reusable Components. There's a lot of duplication throughout!

### Deployment & Functionality

**Score: Performing**

You've got a lot of functionality here! See the issues I created on both repos for some tips and thoughts on how things are implemented.

### Planning / Process / Submission

**Score: Excelling**

Really great to see y'all following Git Flow! A general tip is to just have the feature name in the fature branch (not your own names) and to keep them short (maybe 2-3 words max. Also avoid using "reserved words" like `develop` in branche names - you have a `develop` branch and it's important, so it could be confusing to have any other branches that also have `develop` in the name. Otherwise, it looks like y'all did a good job of following the workflow.
